const GRID_STEP = 10
const GRID_LINE_WIDTH = 1
const GRID_COLOR = '#001000'
const PIXEL_COLOR = '#00ff00'
const PIXEL_SIZE = GRID_STEP - 2 * GRID_LINE_WIDTH

export {
  GRID_STEP,
  GRID_LINE_WIDTH,
  GRID_COLOR,
  PIXEL_COLOR,
  PIXEL_SIZE
}
